apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  secretName: mysql-secret # Секрет с учетными данными для MySQL
  version: "8.0.32"        # Версия MySQL
  instances: 3             # Количество реплик в кластере
  tlsUseSelfSigned: true   # Использовать самоподписанные сертификаты
  service:
    type: ClusterIP        # Тип сервиса
    defaultPort: mysql-rw  # Порт для чтения и записи
  backups:
    schedule: "*/5 * * * *" # Расписание резервного копирования
    storages:
      - name: backup-storage
        persistentVolumeClaim:
          storageClassName: "standard" # Замените на ваш StorageClass
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
