apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  minimumReplicas: 3
  mysqlVersion: "8.0.0"
  secretRef:
    name: mysql-secret
  backupPolicy:
    enabled: true
    schedule: "*/5 * * * *"
    storageClassName: "standard" 
    volumeSize: 1Gi

