apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  name: mysql-secret
  instances: 3
  mysqlVersion: "8.0"  
 # topology:
  #  mode: "SinglePrimary"  
  router:
    instances: 1

