apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  secretName: mysql-secret # Секрет с учетными данными для MySQL
  version: "8.0.32"        # Версия MySQL
  instances: 3             # Количество реплик в кластере
  tlsUseSelfSigned: true   # Использовать самоподписанные сертификаты
  service:
    type: ClusterIP        # Тип сервиса
    defaultPort: mysql-rw  # Порт для чтения и записи
  backupProfiles:       
    - name: myfancyprofile  # Embedded backup profile
      dumpInstance:         # MySQL Shell Dump
        dumpOptions:
          excludeTables:
          - world.country   # Example to exclude one table 
        storage:
          persistentVolumeClaim:
              claimName: myexample-pvc # store to this pre-existing PVC
  backupSchedules:
    - name: mygreatschedule
      schedule: "*/5 * * * *" 
      backupProfileName:  myfancyprofile # reference the desired backupProfiles's name 
      enabled: true # backup schedules can be temporarily disabled
