apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  members: 3
  version: "8.0.0"  
  secretRef:
    name: mysql-secret
  backup:
    enabled: true
    schedule: "*/5 * * * *"
    storages:
      - storageName: default
        storageClassName: "standard" 
        volumeSize: "1Gi"
