apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mysql-secret
  instances: 3  
  Version: "8.0"  
  router:
    instances: 1
  tlsUseSelfSigned: false


