apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: default
spec:
  instances: 3
  mysqlVersion: "8.0"  
  topology:
    mode: "SinglePrimary"  
  router:
    instances: 2
  storage:
    dataVolumeClaimTemplate:
      metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  secret:
    name: mysql-secret
